export const courseData = [
    {
        id: "01",
        title: "The Complete Web Developer Course",
        image: "https://img-a.udemycdn.com/course/240x135/764164_de03_2.jpg?2UmzrbdAsZemQqQlVwoN8PZN7b4ebILF4DtlUZGTW5f3OuOE9TEt3vXOsTEwjP_OivLrbi_9SO_8tcatmtAFf4Fkcy1OV0WURE10ght9K3GYBNciESI_0bdGKXMFGqI",
        price: 59,
        sale: .3,
        instructor: 'Forhadul Islam',
        description: "COMPLETELY REDONE - The only course you need to learn web development - HTML, CSS, JS, Node, and More!",
        features: [
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "Variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        ]
    },
    {
        id: "02",
        title: "The Complete JavaScript Course 2020: From Zero to Expert!",
        image: "https://img-a.udemycdn.com/course/240x135/1463348_52a4_2.jpg?b3YV7ddcOpcRagTdfxeFcpNaeC042RSMJxbDBf7B93xO5dtaLj0TthPVU3ba5grCaSg25C3o01MgKddw3MNaWNV7AzpJBcixcomahcmkVmlDHRMZU1Ld9xyAq56sIaf4",
        price: 49,
        sale: false,
        instructor: 'Mizanur Rahaman',
        description: "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!",
        features: [
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "Variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        ]
    },
    {
        id: "03",
        title: "React - The Complete Guide (incl Hooks, React Router, Redux)",
        image: "https://img-a.udemycdn.com/course/240x135/2395488_bd78_2.jpg?ZGqwLAVQ4HPygWSko9DqD0bjZw3_pom6FHYn3zk6euGpSHgPd7eKfTdLlJFzGdY8ZJlp3nMMJanLoviySZxPR2J766Z0iuCqgGfhhszWNa_Y1qWYQBG8vvQ70mTGZ3Av",
        price: 69,
        sale: false,
        instructor: 'Mizanur Rahaman',
        description: "Dive in and learn React.js from scratch! Learn Reactjs, Hooks, Redux, React Routing, Animations, Next.js and way more!",
        features: [
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "Variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        ]
    },
    {
        id: "04",
        title: "The Complete Node.js Developer Course ",
        image: "https://img-a.udemycdn.com/course/240x135/1638522_fbdf.jpg?433BBBfyonTBwqvSw_qAPURCHz43Ho9DlbvEdh0rOQgcjLOKUN5O8Mzd9cHvZaDMvdM4lbnfO7SBVGuaYgADmoCTqIcsIdqrzmkJuQPT_GLGRenvxFnZNDXPrsTApA",
        price: 69,
        sale: .25,
        instructor: 'Mizanur Rahaman',
        description: "Learn to build fast, scalable and secure RESTful services with Node, Express and MongoDB, from setup to production",
        features: [
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "Variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        ]
    },
    {
        id: "05",
        title: "MERN Stack Front To Back: Full Stack React, Redux & Node.js",
        image: "https://img-a.udemycdn.com/course/240x135/1254420_f6cb_4.jpg?nNQL_Dt6QYBR6JWnlQdpw3W8HlHa7kvsAk1hg6qi8Vl7l_RBjcKu03vsrDNonFjlTps7basr0Mnz5Wq_GtP18a14l3guCLMmHJUFBaSNwsZGT9Kp4vyxQwCPKPvoFWy3",
        price: 99,
        sale: .2,
        instructor: 'Mizanur Rahaman',
        description: "Build and deploy a social network with Node.js, Express, React, Redux & MongoDB.",
        features: [
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "Variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        ]
    },
    {
        id: "06",
        title: "The Complete WordPress Website Business Course",
        image: "https://img-a.udemycdn.com/course/240x135/520116_edf5_2.jpg?QuBsla9-ZR0NyclHYMclvBLysszjlAwB6SNC6C22znDO4kZQ7GIJvwp6_WE05Ti4C1dsO9qEi2v8xcSYNOuu8dj8SWh4KEcOCqBuLCRDerF5wGUfPD2dkvb8sueV3QQ",
        price: 59,
        sale: .1,
        instructor: 'Mizanur Rahaman',
        description: "Master WordPress with this Complete WordPress Course, without learning how to code and without any programming!",
        features: [
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "Variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "Contrary to popular belief, Lorem Ipsum is not simply random text.",
            "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
            "All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet.",
        ]
    },
    // {
    //     id: "07",
    //     title: "PHP for Beginners - Become a PHP Master - CMS Project",
    //     image: "https://img-b.udemycdn.com/course/240x135/1399390_4a26_2.jpg?secure=9QtgUgMe3V-hp6LocA0nxA%3D%3D%2C1606363580",
    //     price: 59,
    //     description: "PHP for Beginners: learn everything you need to become a professional PHP developer with practical exercises & projects."
    // },
]